"""
make_report.py
---------------
Builds the full Project Report PDF (report.pdf) following the 15-section
structure required by the assignment, embedding the diagrams generated by
make_diagrams.py and the evaluation results produced by the toolkit.
"""

import json
import os
import glob
from datetime import date

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Image, Table, TableStyle,
    ListFlowable, ListItem,
)
from reportlab.lib import colors

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(BASE, "assets")
REPORTS_DIR = os.path.join(BASE, "reports")
OUT_PDF = os.path.join(BASE, "Project_Report.pdf")

# Load the most recent evaluation JSON
json_files = sorted(glob.glob(os.path.join(REPORTS_DIR, "evaluation_*.json")))
with open(json_files[-1]) as f:
    results = json.load(f)

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="CoverTitle", fontSize=26, leading=32, alignment=TA_CENTER, spaceAfter=14, fontName="Helvetica-Bold"))
styles.add(ParagraphStyle(name="CoverSub", fontSize=16, leading=21, alignment=TA_CENTER, spaceAfter=8))
styles.add(ParagraphStyle(name="H1", fontSize=26, leading=31, spaceBefore=18, spaceAfter=10, fontName="Helvetica-Bold"))
styles.add(ParagraphStyle(name="H2", fontSize=22, leading=27, spaceBefore=10, spaceAfter=6, fontName="Helvetica-Bold"))
styles.add(ParagraphStyle(name="Body", fontSize=20, leading=25, spaceAfter=10))
styles.add(ParagraphStyle(name="Caption", fontSize=14, leading=18, alignment=TA_CENTER, textColor=colors.grey, spaceAfter=14))

story = []

# ---------------------------------------------------------------------
# 1. Cover Page
# ---------------------------------------------------------------------
story.append(Spacer(1, 4 * cm))
story.append(Paragraph("Spam Classifier &amp; Model Comparison Toolkit", styles["CoverTitle"]))
story.append(Paragraph("Project Report", styles["CoverSub"]))
story.append(Spacer(1, 1.5 * cm))
story.append(Paragraph("Course: Fundamentals of AI and ML", styles["CoverSub"]))
story.append(Paragraph("Submission Type: Build Your Own Project (Flipped Course Evaluation)", styles["CoverSub"]))
story.append(Paragraph(f"Date: {date.today().strftime('%B %d, %Y')}", styles["CoverSub"]))
story.append(Spacer(1, 2 * cm))
story.append(Paragraph("Name: Kurra Sanjay", styles["CoverSub"]))
story.append(Paragraph("Registration Number: 25MIM10079", styles["CoverSub"]))
story.append(PageBreak())

# ---------------------------------------------------------------------
# 2. Introduction
# ---------------------------------------------------------------------
story.append(Paragraph("2. Introduction", styles["H1"]))
story.append(Paragraph(
    "Spam messages are unsolicited, often malicious text sent in bulk via SMS or email. "
    "They range from harmless advertising to phishing scams that attempt to steal "
    "personal or financial information. This project applies core Machine Learning "
    "concepts covered in the course &mdash; text feature extraction, supervised classification, "
    "model evaluation, and comparison &mdash; to build a working spam-detection toolkit that "
    "can be run entirely from the command line.", styles["Body"]))

# ---------------------------------------------------------------------
# 3. Problem Statement
# ---------------------------------------------------------------------
story.append(Paragraph("3. Problem Statement", styles["H1"]))
story.append(Paragraph(
    "Manually filtering spam does not scale with the volume of messages users receive "
    "daily. An automated, content-based classifier is required that can learn the "
    "linguistic patterns typical of spam messages (urgency, prize offers, suspicious "
    "links, requests for calls/replies) and separate them from legitimate (&ldquo;ham&rdquo;) "
    "messages with high accuracy.", styles["Body"]))

# ---------------------------------------------------------------------
# 4. Functional Requirements
# ---------------------------------------------------------------------
story.append(Paragraph("4. Functional Requirements", styles["H1"]))
func_reqs = [
    "Load and validate a labelled dataset of messages (label, message columns).",
    "Clean raw text and convert it into TF-IDF numeric features.",
    "Train three classical ML models: Naive Bayes, Logistic Regression, Random Forest.",
    "Evaluate every model on a held-out test set (accuracy, precision, recall, F1, confusion matrix).",
    "Print a comparison table and automatically identify the best-performing model.",
    "Persist evaluation results as a timestamped JSON report.",
    "Classify a single ad-hoc, user-supplied message from the command line.",
]
story.append(ListFlowable([ListItem(Paragraph(r, styles["Body"])) for r in func_reqs], bulletType="bullet"))

# ---------------------------------------------------------------------
# 5. Non-Functional Requirements
# ---------------------------------------------------------------------
story.append(Paragraph("5. Non-Functional Requirements", styles["H1"]))
nfrs = [
    ("Performance", "TF-IDF feature extraction is capped at 3000 features (config.MAX_FEATURES) to bound memory/CPU use on modest hardware."),
    ("Reliability", "Custom exceptions (DatasetError, ModelNotFoundError, ModelNotTrainedError) catch invalid states early with clear messages instead of crashing with raw tracebacks."),
    ("Maintainability", "Each concern (config, logging, preprocessing, modeling, evaluation, CLI) lives in its own module with a single responsibility, and hyperparameters are centralized in config.py."),
    ("Logging / Monitoring", "A shared logger writes timestamped INFO/ERROR messages to both the console and logs/app.log for traceability."),
    ("Scalability", "New models can be added by registering them in model.py's _MODEL_REGISTRY without touching any other module (open/closed principle)."),
    ("Usability", "A single, documented CLI command (python -m src.main) runs the entire pipeline; --data and --message flags cover the common use cases."),
    ("Security", "Input validation in preprocessing.py rejects malformed rows/columns before they reach the ML models, reducing the risk of crashes from adversarial or corrupted input."),
]
nfr_table_data = [["Attribute", "How it is addressed"]] + [[a, b] for a, b in nfrs]
t = Table(nfr_table_data, colWidths=[3.2 * cm, 12.3 * cm])
t.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a4d8f")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("FONTSIZE", (0, 0), (-1, -1), 8.5),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f6fc")]),
    ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
]))
story.append(t)
story.append(PageBreak())

# ---------------------------------------------------------------------
# 6. System Architecture
# ---------------------------------------------------------------------
story.append(Paragraph("6. System Architecture", styles["H1"]))
story.append(Paragraph(
    "The system follows a simple layered architecture: a CLI layer accepts user "
    "commands, delegates to the preprocessing module to prepare data, passes the "
    "features to the model-training module, and finally to the evaluation module for "
    "scoring and reporting. Config, logging, and exception handling are cross-cutting "
    "concerns used by every layer.", styles["Body"]))
story.append(Image(os.path.join(ASSETS, "architecture.png"), width=15.5 * cm, height=8.6 * cm))
story.append(Paragraph("Figure 1: System Architecture Diagram", styles["Caption"]))

# ---------------------------------------------------------------------
# 7. Design Diagrams
# ---------------------------------------------------------------------
story.append(Paragraph("7. Design Diagrams", styles["H1"]))

story.append(Paragraph("7.1 Use Case Diagram", styles["H2"]))
story.append(Image(os.path.join(ASSETS, "usecase.png"), width=11 * cm, height=7.9 * cm))
story.append(Paragraph("Figure 2: Use Case Diagram", styles["Caption"]))

story.append(Paragraph("7.2 Workflow Diagram", styles["H2"]))
story.append(Image(os.path.join(ASSETS, "workflow.png"), width=15.5 * cm, height=5.5 * cm))
story.append(Paragraph("Figure 3: Process Flow / Workflow Diagram", styles["Caption"]))
story.append(PageBreak())

story.append(Paragraph("7.3 Sequence Diagram", styles["H2"]))
story.append(Image(os.path.join(ASSETS, "sequence.png"), width=15.5 * cm, height=9.5 * cm))
story.append(Paragraph("Figure 4: Sequence Diagram — Training &amp; Evaluation Flow", styles["Caption"]))

story.append(Paragraph("7.4 Class / Component Diagram", styles["H2"]))
story.append(Image(os.path.join(ASSETS, "class_diagram.png"), width=15.5 * cm, height=9.0 * cm))
story.append(Paragraph("Figure 5: Class / Component Diagram", styles["Caption"]))

story.append(Paragraph(
    "No ER/database schema diagram is included because this project persists data "
    "to flat CSV/JSON files rather than a relational database; this is noted as a "
    "possible future enhancement in Section 14.", styles["Body"]))
story.append(PageBreak())

# ---------------------------------------------------------------------
# 8. Design Decisions & Rationale
# ---------------------------------------------------------------------
story.append(Paragraph("8. Design Decisions &amp; Rationale", styles["H1"]))
decisions = [
    "TF-IDF over raw word counts: TF-IDF down-weights very common words, giving more informative features for short, informal messages.",
    "Three complementary models: Naive Bayes (fast, strong baseline for text), Logistic Regression (linear, interpretable), Random Forest (non-linear, robust to noise) &mdash; comparing them demonstrates model-selection skills rather than committing to a single algorithm.",
    "CLI over GUI: satisfies the assignment's command-line executability requirement and keeps the project dependency-light and easy to evaluate/automate.",
    "Custom exception hierarchy: makes failure modes explicit (bad dataset vs. untrained model vs. unknown model name) instead of relying on generic tracebacks.",
    "Central config.py: avoids hard-coded constants scattered across files, so hyperparameters can be tuned in one place.",
]
story.append(ListFlowable([ListItem(Paragraph(d, styles["Body"])) for d in decisions], bulletType="bullet"))

# ---------------------------------------------------------------------
# 9. Implementation Details
# ---------------------------------------------------------------------
story.append(Paragraph("9. Implementation Details", styles["H1"]))
story.append(Paragraph(
    "The project is implemented in Python 3 using pandas and scikit-learn. "
    "<b>preprocessing.py</b> loads and validates the CSV dataset, lowercases and strips "
    "punctuation/digits from each message, and fits a TfidfVectorizer (max 3000 features) "
    "before splitting into stratified train/test sets (75/25). <b>model.py</b> defines a "
    "SpamClassifier wrapper class and a registry dictionary mapping model names to "
    "scikit-learn estimators, so new algorithms can be added with one line. <b>evaluate.py</b> "
    "computes weighted precision/recall/F1 (appropriate even if classes become imbalanced), "
    "builds a confusion matrix per model, prints an aligned comparison table, and writes a "
    "timestamped JSON report to reports/. <b>main.py</b> wires everything together behind an "
    "argparse-based CLI, with try/except around the pipeline to surface SpamToolkitError "
    "subclasses as clean, user-facing error messages.", styles["Body"]))
story.append(Paragraph("Repository layout (5-10 meaningful modules, as required):", styles["Body"]))
files = [
    "src/config.py — configuration constants",
    "src/logger.py — centralized logging setup",
    "src/exceptions.py — custom exception hierarchy",
    "src/preprocessing.py — Module 1: data cleaning &amp; feature extraction",
    "src/model.py — Module 2: model training &amp; prediction",
    "src/evaluate.py — Module 3: evaluation &amp; reporting",
    "src/main.py — CLI entry point",
    "scripts/generate_sample_data.py — sample dataset generator",
    "tests/test_toolkit.py — automated unit tests (8 tests)",
]
story.append(ListFlowable([ListItem(Paragraph(f, styles["Body"])) for f in files], bulletType="bullet"))

# ---------------------------------------------------------------------
# 10. Screenshots / Results
# ---------------------------------------------------------------------
story.append(PageBreak())
story.append(Paragraph("10. Screenshots / Results", styles["H1"]))
story.append(Paragraph("Console output from running <b>python -m src.main</b> on the bundled sample dataset:", styles["Body"]))

metric_rows = [["Model", "Accuracy", "Precision", "Recall", "F1-score"]]
for name, m in results.items():
    metric_rows.append([name, m["accuracy"], m["precision"], m["recall"], m["f1_score"]])
mt = Table(metric_rows, colWidths=[5 * cm, 2.6 * cm, 2.6 * cm, 2.6 * cm, 2.6 * cm])
mt.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a4d8f")),
    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
    ("FONTSIZE", (0, 0), (-1, -1), 9),
    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ("ALIGN", (1, 0), (-1, -1), "CENTER"),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f6fc")]),
    ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
]))
story.append(mt)
story.append(Spacer(1, 0.3 * cm))
story.append(Paragraph(
    "All three models score very highly on the bundled sample dataset. This dataset is "
    "synthetically generated from a small set of templates (see Section 12), so scores "
    "this high are expected on this data and are not representative of performance on "
    "real-world messages &mdash; see Section 12 for discussion.", styles["Body"]))

# ---------------------------------------------------------------------
# 11. Testing Approach
# ---------------------------------------------------------------------
story.append(Paragraph("11. Testing Approach", styles["H1"]))
story.append(Paragraph(
    "Automated unit tests (pytest) validate each module in isolation: text cleaning "
    "behaviour, dataset validation (missing file, missing columns), the end-to-end "
    "preprocessing pipeline, and model training/prediction — including that the correct "
    "custom exceptions are raised for an unknown model name and for predicting before "
    "training. All 8 tests pass (<b>pytest tests/ -v</b>). Manual/system testing was also "
    "performed by running the CLI end-to-end with the bundled dataset and with custom "
    "ad-hoc messages to confirm sensible spam/ham predictions.", styles["Body"]))

# ---------------------------------------------------------------------
# 12. Challenges Faced
# ---------------------------------------------------------------------
story.append(Paragraph("12. Challenges Faced", styles["H1"]))
story.append(Paragraph(
    "Sourcing a ready-to-use, offline labelled dataset was the main practical challenge, "
    "so a template-based synthetic dataset generator was written instead. This makes the "
    "project fully self-contained and reproducible, but also means the reported accuracy "
    "is optimistic (the vocabulary of spam vs. ham templates is quite distinct). Choosing "
    "an evaluation metric that stays meaningful if classes become imbalanced (weighted "
    "precision/recall/F1 rather than plain accuracy) was another design consideration.", styles["Body"]))

# ---------------------------------------------------------------------
# 13. Learnings & Key Takeaways
# ---------------------------------------------------------------------
story.append(Paragraph("13. Learnings &amp; Key Takeaways", styles["H1"]))
learnings = [
    "How to structure a small ML project into clean, testable modules rather than one script.",
    "Practical experience comparing generative (Naive Bayes) vs. discriminative (Logistic Regression) vs. ensemble (Random Forest) classifiers on the same text-classification task.",
    "Why TF-IDF is a strong, lightweight baseline feature representation for short text.",
    "The importance of validating input data and raising specific exceptions early, rather than letting errors surface deep inside a pipeline.",
]
story.append(ListFlowable([ListItem(Paragraph(l, styles["Body"])) for l in learnings], bulletType="bullet"))

# ---------------------------------------------------------------------
# 14. Future Enhancements
# ---------------------------------------------------------------------
story.append(Paragraph("14. Future Enhancements", styles["H1"]))
future = [
    "Replace the synthetic dataset with a large real-world corpus (e.g. UCI SMS Spam Collection) for realistic evaluation.",
    "Add a persistence layer (SQLite) to store classification history, with an accompanying ER diagram.",
    "Expose the toolkit through a lightweight REST API or web UI for non-CLI users.",
    "Add cross-validation and hyperparameter tuning (GridSearchCV) instead of fixed defaults.",
    "Experiment with word embeddings or transformer-based models as a stretch goal beyond the classical-ML syllabus.",
]
story.append(ListFlowable([ListItem(Paragraph(f, styles["Body"])) for f in future], bulletType="bullet"))

# ---------------------------------------------------------------------
# 15. References
# ---------------------------------------------------------------------
story.append(Paragraph("15. References", styles["H1"]))
refs = [
    "Pedregosa et al., \"Scikit-learn: Machine Learning in Python\", JMLR 12, 2011.",
    "McKinney, W., \"Data Structures for Statistical Computing in Python\", SciPy 2010 (pandas).",
    "UCI Machine Learning Repository — SMS Spam Collection Dataset (reference dataset for future enhancement).",
    "Scikit-learn documentation: https://scikit-learn.org/stable/",
]
story.append(ListFlowable([ListItem(Paragraph(r, styles["Body"])) for r in refs], bulletType="bullet"))

doc = SimpleDocTemplate(
    OUT_PDF, pagesize=A4,
    leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    title="Spam Classifier & Model Comparison Toolkit — Project Report",
)
doc.build(story)
print("Wrote", OUT_PDF)
